/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Identity.Api.UserInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Microsoft.AspNetCore.Identity.Data.RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Http.HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    useCookies?: components["schemas"]["System.Nullable`1[[System.Boolean, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"];
                    useSessionCookies?: components["schemas"]["System.Nullable`1[[System.Boolean, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Microsoft.AspNetCore.Identity.Data.LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Authentication.BearerToken.AccessTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Microsoft.AspNetCore.Identity.Data.RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Authentication.BearerToken.AccessTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/confirmEmail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MapIdentityApi-/confirmEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resendConfirmationEmail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Microsoft.AspNetCore.Identity.Data.ResendConfirmationEmailRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forgotPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Microsoft.AspNetCore.Identity.Data.ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Http.HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resetPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Microsoft.AspNetCore.Identity.Data.ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Http.HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/2fa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Microsoft.AspNetCore.Identity.Data.TwoFactorRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Identity.Data.TwoFactorResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Http.HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Identity.Data.InfoResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Http.HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Microsoft.AspNetCore.Identity.Data.InfoRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Identity.Data.InfoResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Microsoft.AspNetCore.Http.HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Content/BlogPost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Content.Core.DTOs.BlogPosts.CreateBlogPostRequest"];
                    "text/json": components["schemas"]["Content.Core.DTOs.BlogPosts.CreateBlogPostRequest"];
                    "application/*+json": components["schemas"]["Content.Core.DTOs.BlogPosts.CreateBlogPostRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Content/BlogPost/{title}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    title: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    title: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Content.Core.DTOs.BlogPosts.UpdateBlogPostRequest"];
                    "text/json": components["schemas"]["Content.Core.DTOs.BlogPosts.UpdateBlogPostRequest"];
                    "application/*+json": components["schemas"]["Content.Core.DTOs.BlogPosts.UpdateBlogPostRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    title: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Content/Files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Content.Core.DTOs.ContentFiles.CreateContentFileRequest"];
                    "text/json": components["schemas"]["Content.Core.DTOs.ContentFiles.CreateContentFileRequest"];
                    "application/*+json": components["schemas"]["Content.Core.DTOs.ContentFiles.CreateContentFileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Content/Files/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Content.Core.DTOs.ContentFiles.UpdateContentFileRequest"];
                    "text/json": components["schemas"]["Content.Core.DTOs.ContentFiles.UpdateContentFileRequest"];
                    "application/*+json": components["schemas"]["Content.Core.DTOs.ContentFiles.UpdateContentFileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Content/Menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Content.Core.DTOs.Menus.CreateMenuRequest"];
                    "text/json": components["schemas"]["Content.Core.DTOs.Menus.CreateMenuRequest"];
                    "application/*+json": components["schemas"]["Content.Core.DTOs.Menus.CreateMenuRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Content/Menu/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Content.Core.DTOs.Menus.UpdateMenuRequest"];
                    "text/json": components["schemas"]["Content.Core.DTOs.Menus.UpdateMenuRequest"];
                    "application/*+json": components["schemas"]["Content.Core.DTOs.Menus.UpdateMenuRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Content/MetaObject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Content.Core.DTOs.MetaObjects.CreateMetaObjectRequest"];
                    "text/json": components["schemas"]["Content.Core.DTOs.MetaObjects.CreateMetaObjectRequest"];
                    "application/*+json": components["schemas"]["Content.Core.DTOs.MetaObjects.CreateMetaObjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Content/MetaObject/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Content.Core.DTOs.MetaObjects.UpdateMetaObjectRequest"];
                    "text/json": components["schemas"]["Content.Core.DTOs.MetaObjects.UpdateMetaObjectRequest"];
                    "application/*+json": components["schemas"]["Content.Core.DTOs.MetaObjects.UpdateMetaObjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/seed-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Identity.Api.AdminAccountInput"];
                    "text/json": components["schemas"]["Identity.Api.AdminAccountInput"];
                    "application/*+json": components["schemas"]["Identity.Api.AdminAccountInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/seed-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/categories/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Categories.UpdateCategoryRequest"];
                    "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Categories.UpdateCategoryRequest"];
                    "application/*+json": components["schemas"]["ProductCatalog.Core.DTOs.Categories.UpdateCategoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/categories/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Categories.CreateCategoryRequest"];
                    "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Categories.CreateCategoryRequest"];
                    "application/*+json": components["schemas"]["ProductCatalog.Core.DTOs.Categories.CreateCategoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Collections.CreateCollectionRequest"];
                    "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Collections.CreateCollectionRequest"];
                    "application/*+json": components["schemas"]["ProductCatalog.Core.DTOs.Collections.CreateCollectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/collections/{title}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    title: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    title: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Collections.UpdateCollectionRequest"];
                    "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Collections.UpdateCollectionRequest"];
                    "application/*+json": components["schemas"]["ProductCatalog.Core.DTOs.Collections.UpdateCollectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    title: components["schemas"]["System.String"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/collections/{title}/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    title: components["schemas"]["System.String"];
                    productId: components["schemas"]["System.Int32"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    title: components["schemas"]["System.String"];
                    productId: components["schemas"]["System.Int32"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/inventory/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                        "application/json": components["schemas"]["System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                        "text/json": components["schemas"]["System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/inventory/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: components["schemas"]["System.Int32"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse"];
                        "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse"];
                        "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: components["schemas"]["System.Int32"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.UpdateProductInventoryRequest"];
                    "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.UpdateProductInventoryRequest"];
                    "application/*+json": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.UpdateProductInventoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse"];
                        "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse"];
                        "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/inventory/products/{productId}/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: components["schemas"]["System.Int32"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.AdjustProductInventoryRequest"];
                    "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.AdjustProductInventoryRequest"];
                    "application/*+json": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.AdjustProductInventoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse"];
                        "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse"];
                        "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    PageNumber?: components["schemas"]["System.Int32"];
                    PageSize?: components["schemas"]["System.Int32"];
                    Search?: components["schemas"]["System.String"];
                    CategoryName?: components["schemas"]["System.String"];
                    Status?: components["schemas"]["System.Nullable`1[[ProductCatalog.Core.Entities.ProductStatus, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                    SortBy?: components["schemas"]["System.String"];
                    SortDirection?: components["schemas"]["System.String"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SharedKernel.DTOs.PaginatedList`1[[ProductCatalog.Core.DTOs.Products.ProductResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                        "application/json": components["schemas"]["SharedKernel.DTOs.PaginatedList`1[[ProductCatalog.Core.DTOs.Products.ProductResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                        "text/json": components["schemas"]["SharedKernel.DTOs.PaginatedList`1[[ProductCatalog.Core.DTOs.Products.ProductResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.CreateProductRequest"];
                    "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.CreateProductRequest"];
                    "application/*+json": components["schemas"]["ProductCatalog.Core.DTOs.Products.CreateProductRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductCatalog.Core.DTOs.Products.ProductResponse"];
                        "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.ProductResponse"];
                        "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.ProductResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["System.Int32"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductCatalog.Core.DTOs.Products.ProductResponse"];
                        "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.ProductResponse"];
                        "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.ProductResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["System.Int32"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.UpdateProductRequest"];
                    "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.UpdateProductRequest"];
                    "application/*+json": components["schemas"]["ProductCatalog.Core.DTOs.Products.UpdateProductRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductCatalog.Core.DTOs.Products.ProductResponse"];
                        "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.ProductResponse"];
                        "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.ProductResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["System.Int32"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/products/{id}/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["System.Int32"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Products.OptionResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                        "application/json": components["schemas"]["System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Products.OptionResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                        "text/json": components["schemas"]["System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Products.OptionResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["System.Int32"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.CreateOptionRequest"];
                    "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.CreateOptionRequest"];
                    "application/*+json": components["schemas"]["ProductCatalog.Core.DTOs.Products.CreateOptionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductCatalog.Core.DTOs.Products.OptionResponse"];
                        "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.OptionResponse"];
                        "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.OptionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/products/{id}/options/{optionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["System.Int32"];
                    optionId: components["schemas"]["System.Int32"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/products/{id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["System.Int32"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Products.VariantResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                        "application/json": components["schemas"]["System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Products.VariantResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                        "text/json": components["schemas"]["System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Products.VariantResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["System.Int32"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.CreateVariantRequest"];
                    "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.CreateVariantRequest"];
                    "application/*+json": components["schemas"]["ProductCatalog.Core.DTOs.Products.CreateVariantRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductCatalog.Core.DTOs.Products.VariantResponse"];
                        "application/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.VariantResponse"];
                        "text/json": components["schemas"]["ProductCatalog.Core.DTOs.Products.VariantResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ProductCatalog/products/{id}/variants/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["System.Int32"];
                    variantId: components["schemas"]["System.Int32"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Content.Core.DTOs.BlogPosts.CreateBlogPostRequest": {
            title: components["schemas"]["System.String"];
            slug?: null | components["schemas"]["System.String"];
            content: components["schemas"]["System.String"];
            summary?: components["schemas"]["System.String"];
            imageUrl?: components["schemas"]["System.String"];
            status?: components["schemas"]["Content.Core.Entities.BlogPostStatus"];
        };
        "Content.Core.DTOs.BlogPosts.UpdateBlogPostRequest": {
            slug?: null | components["schemas"]["System.String"];
            content: components["schemas"]["System.String"];
            summary?: components["schemas"]["System.String"];
            imageUrl?: components["schemas"]["System.String"];
            status?: components["schemas"]["Content.Core.Entities.BlogPostStatus"];
        };
        "Content.Core.DTOs.ContentFiles.CreateContentFileRequest": {
            name: components["schemas"]["System.String"];
            url: components["schemas"]["System.String"];
            contentType?: components["schemas"]["System.String"];
            size?: components["schemas"]["System.Int64"];
        };
        "Content.Core.DTOs.ContentFiles.UpdateContentFileRequest": {
            url: components["schemas"]["System.String"];
            contentType?: components["schemas"]["System.String"];
            size?: components["schemas"]["System.Int64"];
        };
        "Content.Core.DTOs.Menus.CreateMenuRequest": {
            name: components["schemas"]["System.String"];
            description?: components["schemas"]["System.String"];
            url: components["schemas"]["System.String"];
            parentName?: null | components["schemas"]["System.String"];
        };
        "Content.Core.DTOs.Menus.UpdateMenuRequest": {
            description?: components["schemas"]["System.String"];
            url: components["schemas"]["System.String"];
            parentName?: null | components["schemas"]["System.String"];
        };
        "Content.Core.DTOs.MetaObjects.CreateMetaObjectRequest": {
            key: components["schemas"]["System.String"];
            namespace: components["schemas"]["System.String"];
            value: components["schemas"]["System.String"];
            type: components["schemas"]["System.String"];
        };
        "Content.Core.DTOs.MetaObjects.UpdateMetaObjectRequest": {
            namespace: components["schemas"]["System.String"];
            value: components["schemas"]["System.String"];
            type: components["schemas"]["System.String"];
        };
        "Content.Core.Entities.BlogPostStatus": number;
        "Identity.Api.AdminAccountInput": {
            email?: components["schemas"]["System.String"];
            password?: components["schemas"]["System.String"];
        };
        "Identity.Api.UserInfo": {
            email?: components["schemas"]["System.String"];
            role?: components["schemas"]["System.String"];
            name?: components["schemas"]["System.String"];
        };
        "Microsoft.AspNetCore.Authentication.BearerToken.AccessTokenResponse": {
            tokenType?: components["schemas"]["System.String"];
            accessToken: components["schemas"]["System.String"];
            expiresIn: components["schemas"]["System.Int64"];
            refreshToken: components["schemas"]["System.String"];
        };
        "Microsoft.AspNetCore.Http.HttpValidationProblemDetails": {
            type?: null | components["schemas"]["System.String"];
            title?: null | components["schemas"]["System.String"];
            status?: null | components["schemas"]["System.Nullable`1[[System.Int32, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"];
            detail?: null | components["schemas"]["System.String"];
            instance?: null | components["schemas"]["System.String"];
            errors?: components["schemas"]["System.Collections.Generic.IDictionary`2[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String[], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"];
        };
        "Microsoft.AspNetCore.Identity.Data.ForgotPasswordRequest": {
            email: components["schemas"]["System.String"];
        };
        "Microsoft.AspNetCore.Identity.Data.InfoRequest": {
            newEmail?: null | components["schemas"]["System.String"];
            newPassword?: null | components["schemas"]["System.String"];
            oldPassword?: null | components["schemas"]["System.String"];
        };
        "Microsoft.AspNetCore.Identity.Data.InfoResponse": {
            email: components["schemas"]["System.String"];
            isEmailConfirmed: components["schemas"]["System.Boolean"];
        };
        "Microsoft.AspNetCore.Identity.Data.LoginRequest": {
            email: components["schemas"]["System.String"];
            password: components["schemas"]["System.String"];
            twoFactorCode?: null | components["schemas"]["System.String"];
            twoFactorRecoveryCode?: null | components["schemas"]["System.String"];
        };
        "Microsoft.AspNetCore.Identity.Data.RefreshRequest": {
            refreshToken: components["schemas"]["System.String"];
        };
        "Microsoft.AspNetCore.Identity.Data.RegisterRequest": {
            email: components["schemas"]["System.String"];
            password: components["schemas"]["System.String"];
        };
        "Microsoft.AspNetCore.Identity.Data.ResendConfirmationEmailRequest": {
            email: components["schemas"]["System.String"];
        };
        "Microsoft.AspNetCore.Identity.Data.ResetPasswordRequest": {
            email: components["schemas"]["System.String"];
            resetCode: components["schemas"]["System.String"];
            newPassword: components["schemas"]["System.String"];
        };
        "Microsoft.AspNetCore.Identity.Data.TwoFactorRequest": {
            enable?: null | components["schemas"]["System.Nullable`1[[System.Boolean, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"];
            twoFactorCode?: null | components["schemas"]["System.String"];
            resetSharedKey?: components["schemas"]["System.Boolean"];
            resetRecoveryCodes?: components["schemas"]["System.Boolean"];
            forgetMachine?: components["schemas"]["System.Boolean"];
        };
        "Microsoft.AspNetCore.Identity.Data.TwoFactorResponse": {
            sharedKey: components["schemas"]["System.String"];
            recoveryCodesLeft: components["schemas"]["System.Int32"];
            recoveryCodes?: null | components["schemas"]["System.String[]"];
            isTwoFactorEnabled: components["schemas"]["System.Boolean"];
            isMachineRemembered: components["schemas"]["System.Boolean"];
        };
        "ProductCatalog.Core.DTOs.Categories.CreateCategoryRequest": {
            name: components["schemas"]["System.String"];
            description?: components["schemas"]["System.String"];
            imageUrl?: components["schemas"]["System.String"];
            status?: components["schemas"]["ProductCatalog.Core.Entities.CategoryStatus"];
            parentName?: null | components["schemas"]["System.String"];
            slug?: null | components["schemas"]["System.String"];
        };
        "ProductCatalog.Core.DTOs.Categories.UpdateCategoryRequest": {
            description?: components["schemas"]["System.String"];
            imageUrl?: components["schemas"]["System.String"];
            status?: components["schemas"]["ProductCatalog.Core.Entities.CategoryStatus"];
            parentName?: null | components["schemas"]["System.String"];
            slug?: components["schemas"]["System.String"];
        };
        "ProductCatalog.Core.DTOs.Collections.CreateCollectionRequest": {
            title: components["schemas"]["System.String"];
            description?: components["schemas"]["System.String"];
            slug?: components["schemas"]["System.String"];
            image?: components["schemas"]["System.String"];
        };
        "ProductCatalog.Core.DTOs.Collections.UpdateCollectionRequest": {
            description?: components["schemas"]["System.String"];
            slug?: components["schemas"]["System.String"];
            image?: components["schemas"]["System.String"];
        };
        "ProductCatalog.Core.DTOs.Inventory.AdjustProductInventoryRequest": {
            stockChange?: components["schemas"]["System.Int32"];
            soldChange?: components["schemas"]["System.Int32"];
            reservedChange?: components["schemas"]["System.Int32"];
        };
        "ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse": {
            productId?: components["schemas"]["System.Int32"];
            productName?: components["schemas"]["System.String"];
            sku?: components["schemas"]["System.String"];
            barcode?: components["schemas"]["System.String"];
            stock?: components["schemas"]["System.Int32"];
            sold?: components["schemas"]["System.Int32"];
            trackInventory?: components["schemas"]["System.Boolean"];
            lowStockThreshold?: components["schemas"]["System.Int32"];
            allowBackorder?: components["schemas"]["System.Boolean"];
            reserved?: components["schemas"]["System.Int32"];
            availableStock?: components["schemas"]["System.Int32"];
        };
        "ProductCatalog.Core.DTOs.Inventory.UpdateProductInventoryRequest": {
            sku: components["schemas"]["System.String"];
            barcode: components["schemas"]["System.String"];
            stock?: components["schemas"]["System.Int32"];
            sold?: components["schemas"]["System.Int32"];
            trackInventory?: components["schemas"]["System.Boolean"];
            lowStockThreshold?: components["schemas"]["System.Int32"];
            allowBackorder?: components["schemas"]["System.Boolean"];
            reserved?: components["schemas"]["System.Int32"];
        };
        "ProductCatalog.Core.DTOs.Products.CreateOptionRequest": {
            name: components["schemas"]["System.String"];
            displayOrder?: components["schemas"]["System.Int32"];
            values?: components["schemas"]["System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"];
        };
        "ProductCatalog.Core.DTOs.Products.CreateProductRequest": {
            name: components["schemas"]["System.String"];
            description?: components["schemas"]["System.String"];
            categoryName: components["schemas"]["System.String"];
            slug: components["schemas"]["System.String"];
            imageUrl?: components["schemas"]["System.String"];
            status?: components["schemas"]["ProductCatalog.Core.Entities.ProductStatus"];
            price?: components["schemas"]["System.Decimal"];
            compareAtPrice?: components["schemas"]["System.Decimal"];
            costPrice?: components["schemas"]["System.Decimal"];
            chargeTax?: components["schemas"]["System.Boolean"];
            stock?: components["schemas"]["System.Int32"];
            sku: components["schemas"]["System.String"];
            barcode: components["schemas"]["System.String"];
            trackInventory?: components["schemas"]["System.Boolean"];
            lowStockThreshold?: components["schemas"]["System.Int32"];
            allowBackorder?: components["schemas"]["System.Boolean"];
        };
        "ProductCatalog.Core.DTOs.Products.CreateVariantRequest": {
            price?: components["schemas"]["System.Decimal"];
            optionValues?: components["schemas"]["System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Products.VariantOptionValueDto, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
        };
        "ProductCatalog.Core.DTOs.Products.OptionResponse": {
            id?: components["schemas"]["System.Int32"];
            name?: components["schemas"]["System.String"];
            displayOrder?: components["schemas"]["System.Int32"];
            values?: components["schemas"]["System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"];
        };
        "ProductCatalog.Core.DTOs.Products.ProductResponse": {
            id?: components["schemas"]["System.Int32"];
            name?: components["schemas"]["System.String"];
            description?: components["schemas"]["System.String"];
            categoryName?: components["schemas"]["System.String"];
            slug?: components["schemas"]["System.String"];
            imageUrl?: components["schemas"]["System.String"];
            status?: components["schemas"]["ProductCatalog.Core.Entities.ProductStatus"];
            price?: components["schemas"]["System.Decimal"];
            compareAtPrice?: components["schemas"]["System.Decimal"];
            costPrice?: components["schemas"]["System.Decimal"];
            chargeTax?: components["schemas"]["System.Boolean"];
            stock?: components["schemas"]["System.Int32"];
            sku?: components["schemas"]["System.String"];
            trackInventory?: components["schemas"]["System.Boolean"];
            lowStockThreshold?: components["schemas"]["System.Int32"];
            allowBackorder?: components["schemas"]["System.Boolean"];
            sold?: components["schemas"]["System.Int32"];
            reserved?: components["schemas"]["System.Int32"];
        };
        "ProductCatalog.Core.DTOs.Products.UpdateProductRequest": {
            name: components["schemas"]["System.String"];
            description?: components["schemas"]["System.String"];
            categoryName: components["schemas"]["System.String"];
            slug: components["schemas"]["System.String"];
            imageUrl?: components["schemas"]["System.String"];
            status?: components["schemas"]["ProductCatalog.Core.Entities.ProductStatus"];
            price?: components["schemas"]["System.Decimal"];
            compareAtPrice?: components["schemas"]["System.Decimal"];
            costPrice?: components["schemas"]["System.Decimal"];
            chargeTax?: components["schemas"]["System.Boolean"];
            stock?: components["schemas"]["System.Int32"];
            sku: components["schemas"]["System.String"];
            barcode: components["schemas"]["System.String"];
            trackInventory?: components["schemas"]["System.Boolean"];
            lowStockThreshold?: components["schemas"]["System.Int32"];
            allowBackorder?: components["schemas"]["System.Boolean"];
        };
        "ProductCatalog.Core.DTOs.Products.VariantOptionValueDto": {
            optionId?: components["schemas"]["System.Int32"];
            optionName?: components["schemas"]["System.String"];
            value?: components["schemas"]["System.String"];
        };
        "ProductCatalog.Core.DTOs.Products.VariantResponse": {
            id?: components["schemas"]["System.Int32"];
            price?: components["schemas"]["System.Decimal"];
            optionValues?: components["schemas"]["System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Products.VariantOptionValueDto, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
        };
        "ProductCatalog.Core.Entities.CategoryStatus": number;
        "ProductCatalog.Core.Entities.ProductStatus": number;
        "SharedKernel.DTOs.PaginatedList`1[[ProductCatalog.Core.DTOs.Products.ProductResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]": {
            items?: components["schemas"]["System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Products.ProductResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
            pageNumber?: components["schemas"]["System.Int32"];
            totalPages?: components["schemas"]["System.Int32"];
            totalCount?: components["schemas"]["System.Int32"];
            hasPreviousPage?: components["schemas"]["System.Boolean"];
            hasNextPage?: components["schemas"]["System.Boolean"];
        };
        "System.Boolean": boolean;
        "System.Collections.Generic.IDictionary`2[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String[], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]": {
            [key: string]: components["schemas"]["System.String[]"];
        };
        "System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]": components["schemas"]["ProductCatalog.Core.DTOs.Inventory.ProductInventoryResponse"][];
        "System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Products.OptionResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]": components["schemas"]["ProductCatalog.Core.DTOs.Products.OptionResponse"][];
        "System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Products.ProductResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]": components["schemas"]["ProductCatalog.Core.DTOs.Products.ProductResponse"][];
        "System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Products.VariantOptionValueDto, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]": components["schemas"]["ProductCatalog.Core.DTOs.Products.VariantOptionValueDto"][];
        "System.Collections.Generic.List`1[[ProductCatalog.Core.DTOs.Products.VariantResponse, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]": components["schemas"]["ProductCatalog.Core.DTOs.Products.VariantResponse"][];
        "System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]": components["schemas"]["System.String"][];
        /** Format: double */
        "System.Decimal": number | string;
        /** Format: int32 */
        "System.Int32": number;
        /** Format: int64 */
        "System.Int64": number | string;
        "System.Nullable`1[[ProductCatalog.Core.Entities.ProductStatus, ProductCatalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]": number;
        "System.Nullable`1[[System.Boolean, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]": boolean;
        /** Format: int32 */
        "System.Nullable`1[[System.Int32, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]": number | string;
        "System.String": string;
        "System.String[]": components["schemas"]["System.String"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "MapIdentityApi-/confirmEmail": {
        parameters: {
            query: {
                userId: components["schemas"]["System.String"];
                code: components["schemas"]["System.String"];
                changedEmail?: components["schemas"]["System.String"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
